<?php

namespace app\index\controller;

use app\common\model\Article;
use app\common\model\Category;
use app\common\typeCode\VideoCate;
use think\Controller;
use think\Request;
use app\common\model\Article as ArticleModel;
use app\common\typeCode\Video as VideoType;

class Video extends Base
{
    public $cate;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $type = new VideoType();
        $videoCate = new VideoCate();
        $category = new Category();

        
        //热门视频 以及推荐
        $hot_article = (new ArticleModel())->allowData()
            ->where(['type' => $type->articleType])
            ->order('click', 'desc')
            ->limit(8)->field('id,pic,title')->select();

        //合作企业
        $business_parters = explode(',', $this->getConfig('business_parters'));

        //视频分类
        $this->cate = $category->getList($videoCate->cacheName, $videoCate->cateType);

        $this->assign('hot_article', $hot_article);
        $this->assign('business_parters', $business_parters);
        $this->assign('cate', $this->cate);

    }

    public function index(Request $request)
    {
        $id = $request->param('id');
        $type = new VideoType();
        $category = new Category();


        $cateIdActive = $id ?? $this->cate['0']['id'] ?? 0;

        $cateActive = $category->find($cateIdActive);
        //视频列表
        $article = (new ArticleModel())->allowData()
            ->where(['type' => $type->articleType])
            ->where(['cate_id' => $cateIdActive])
            ->order('id', 'desc')
            ->paginate(15);

        $this->assign('cate_active', $cateActive);
        $this->assign('article', $article);

        return $this->fetch();

    }

    public function info(Request $request)
    {
        $id = $request->param('id');

        $article = new Article();
        $article = $article->find($id);
        $article->where(['id'=>$id])->setInc('click');
        $this->assign('article',$article);

        return $this->fetch();
//        $article = (new Ar)
    }
}
